# Generated by Django 4.1 on 2025-04-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SectionPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_id", models.CharField(max_length=100)),
                ("sectionDisplayName", models.CharField(max_length=100)),
                ("sectionType", models.CharField(max_length=100)),
                ("permissions", models.JSONField()),
            ],
            options={
                "db_table": "sectionPermissions",
            },
        ),
    ]
