# Generated by Django 4.1 on 2025-04-02 07:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room', models.TextField(blank=True, null=True)),
                ('product_available', models.TextField(blank=True, null=True)),
                ('prework', models.TextField(blank=True, null=True)),
                ('install', models.TextField(blank=True, null=True)),
                ('post_work', models.TextField(blank=True, null=True)),
                ('day_install_began', models.TextField(blank=True, null=True)),
                ('day_instal_complete', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'install',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.TextField(blank=True, null=True)),
                ('client_id', models.TextField(blank=True, null=True)),
                ('qty_ordered', models.TextField(blank=True, null=True)),
                ('qty_received', models.TextField(blank=True, null=True)),
                ('quantity_installed', models.TextField(blank=True, null=True)),
                ('quantity_available', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='InvitedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(blank=True, default='invited', max_length=50)),
                ('password', models.BinaryField()),
            ],
            options={
                'db_table': 'invited_users',
            },
        ),
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.TextField(blank=True, null=True)),
                ('client_id', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('qty_ordered', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('a', models.TextField(blank=True, null=True)),
                ('a_col', models.TextField(blank=True, null=True)),
                ('a_lo', models.TextField(blank=True, null=True)),
                ('a_lo_dr', models.TextField(blank=True, null=True)),
                ('b', models.TextField(blank=True, null=True)),
                ('c_pn', models.TextField(blank=True, null=True)),
                ('c', models.TextField(blank=True, null=True)),
                ('curva_24', models.TextField(blank=True, null=True)),
                ('curva', models.TextField(blank=True, null=True)),
                ('curva_dis', models.TextField(blank=True, null=True)),
                ('d', models.TextField(blank=True, null=True)),
                ('dlx', models.TextField(blank=True, null=True)),
                ('presidential_suite', models.TextField(blank=True, null=True)),
                ('st_c', models.TextField(blank=True, null=True)),
                ('suite_a', models.TextField(blank=True, null=True)),
                ('suite_b', models.TextField(blank=True, null=True)),
                ('suite_c', models.TextField(blank=True, null=True)),
                ('suite_mini', models.TextField(blank=True, null=True)),
                ('curva_35', models.TextField(blank=True, null=True)),
                ('client_selected', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_data',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt_number', models.IntegerField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room', models.TextField(blank=True, null=True)),
                ('floor', models.TextField(blank=True, null=True)),
                ('king', models.TextField(blank=True, null=True)),
                ('double', models.TextField(blank=True, null=True)),
                ('exec_king', models.TextField(blank=True, null=True)),
                ('bath_screen', models.TextField(blank=True, null=True)),
                ('room_model', models.TextField(blank=True, null=True)),
                ('left_desk', models.TextField(blank=True, null=True)),
                ('right_desk', models.TextField(blank=True, null=True)),
                ('to_be_renovated', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_data',
            },
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_model', models.TextField(blank=True, null=True)),
                ('total', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_model',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase', models.TextField(blank=True, null=True)),
                ('floor', models.TextField(blank=True, null=True)),
                ('production_starts', models.DateTimeField(blank=True, null=True)),
                ('production_ends', models.DateTimeField(blank=True, null=True)),
                ('shipping_depature', models.DateTimeField(blank=True, null=True)),
                ('shipping_arrival', models.DateTimeField(blank=True, null=True)),
                ('custom_clearing_starts', models.DateTimeField(blank=True, null=True)),
                ('custom_clearing_ends', models.DateTimeField(blank=True, null=True)),
                ('arrive_on_site', models.DateTimeField(blank=True, null=True)),
                ('pre_work_starts', models.DateTimeField(blank=True, null=True)),
                ('pre_work_ends', models.DateTimeField(blank=True, null=True)),
                ('install_starts', models.DateTimeField(blank=True, null=True)),
                ('install_ends', models.DateTimeField(blank=True, null=True)),
                ('post_work_starts', models.DateTimeField(blank=True, null=True)),
                ('post_work_ends', models.DateTimeField(blank=True, null=True)),
                ('floor_completed', models.DateTimeField(blank=True, null=True)),
                ('floor_closes', models.DateTimeField(blank=True, null=True)),
                ('floor_opens', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('role', models.CharField(max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='hotel_bot_app.chatsession')),
            ],
        ),
    ]
