# Generated by Django 4.1 on 2025-04-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='checked_on',
            new_name='expected_arrival_date',
        ),
    ]
