# Generated by Django 4.1 on 2025-04-04 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdata',
            name='room_model_id',
            field=models.ForeignKey(blank=True, db_column='room_model_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_bot_app.roommodel'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='qty_ordered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='qty_received',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity_available',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity_installed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
