# Generated by Django 5.2 on 2025-05-06 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0004_issue_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_comments', to='hotel_bot_app.inviteduser'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='hotel_bot_app.inviteduser'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_issues', to='hotel_bot_app.inviteduser'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='observers',
            field=models.ManyToManyField(blank=True, related_name='observed_issues', to='hotel_bot_app.inviteduser'),
        ),
    ]
