# Generated by Django 5.2 on 2025-05-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0005_alter_comment_user_alter_issue_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='related_inventory_items',
            field=models.ManyToManyField(blank=True, related_name='issues', to='hotel_bot_app.inventory', verbose_name='Related Inventory Items'),
        ),
        migrations.AddField(
            model_name='issue',
            name='related_rooms',
            field=models.ManyToManyField(blank=True, related_name='issues', to='hotel_bot_app.roomdata', verbose_name='Related Rooms'),
        ),
    ]
