# Generated by Django 5.2 on 2025-05-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0007_alter_comment_options_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[('ROOM', 'Room'), ('FLOOR', 'Floor')], max_length=10),
        ),
    ]
