# Generated by Django 5.2 on 2025-08-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0018_productdata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelwarehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
