# Generated by Django 5.2 on 2025-09-02 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0019_hotelwarehouse_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_available',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
