# Generated by Django 5.2 on 2025-09-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bot_app', '0020_alter_inventory_quantity_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_available',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
